### ISSUE TITLE
Create a humane tech badge

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/awesome-humane-tech#1]
Create a badge that can be included in github projects that are contained in this awesome list.
I suggest it should have a heart icon and reddish color scheme..

**Someone with some graphics design and SVG skills should be able to create this in a couple of minutes. Would be very thankful!**

**Comment by aschrijver** [comment]
I created an (unoptimized) draft of a Humane Tech badge that repository maintainers may display in their README, when their project is included in this awesome list.

The badge looks as follows (created with my limited graphics design skills :smile: ):

[![Humane Tech](https://raw.githubusercontent.com/engagingspaces/awesome-humane-tech/master/humane-tech-badge_draft.svg?sanitize=true)](https://github.com/engagingspaces/awesome-humane-tech)

WDYT?

**Comment by aschrijver** [comment]
Current badge is good. Just needs optimizing..

**Comment by gkrishnaks** [comment]
Have you tried creating svg with shields.io tool?

Samples I tried in that easy online tool : 
![img](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-Humane%20Tech-red.svg)
![img](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-Ethical%20Tech-blue.svg)

**Comment by aschrijver** [comment]
Closing this for now. The current badge suffices, until - maybe later - we start doing some actual stuff with a Humane Tech certification program.
