### ISSUE TITLE
HT awesome list selection/updation process

### ISSUE THREAD

**Issue by gkrishnaks** [humanetech-community/awesome-humane-tech#16]
Hi
So I have created and merged "pull request template" to master branch here.

Tested it first in my fork and sample PR will look like this from now on when PR raised to our master branch : https://github.com/gkrishnaks/awesome-humane-tech/pull/4  (please check comments in raw form of [template](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/master/pull_request_template.md) )

Wished to add more ideas on process on how to  add/update to the existing list based on community oriented approach :  

-  PR needs to have sufficient details, at least the ones from template
-  Contributor needs to check the COC checkbox in PR - very important. All checkboxes appear at the top of every PR.
-  Prefer Free/Libre software as it's very hard to trust software whose sources cannot be verified if need arises. Very rare exceptions can be made for non-free software only if the community votes and opts for it. 
-  PR can be merged after at least one comment/thoughts regarding add/update of the proposed project from a community member.
-  PR can be raised on behalf of other projects not owned by requester but the template is expected to be followed so we have future reference as to why something was added to HT awesome list. 
- Mindfulness/Async approach is expected as we expect community members to discuss and decide inclusion of a project to HT awesome list based on comments in PR either in Github or if they prefer on a discussion topic in http://community.humanetech.com/ . If requester does not wish to register in CHT, one of us can create a post on their behalf to discuss on public forum there. 
- If a project is created by a HT project member herself,  the requester should not merge to master and await approval before merging. Exceptional cases should be rare where pre-approval decision was made in public accessible channels. Ideally it should be kept rare and PR template + comments structure should be followed for future reference as we are not expected to keep everything in our mind and can always go back and refer.

**Comment by gkrishnaks** [comment]
As another example (and real submission too), I created this Pull Request : https://github.com/humanetech-community/awesome-humane-tech/pull/17

**Comment by aschrijver** [comment]
This looks very good @gkrishnaks though there are some improvements I see that I'd like to add, but this can be done later and there is no hurry.

PS. Great job extending the list!

**Comment by gkrishnaks** [comment]
Yes, anyone can submit a project  for HT evaluation irrespective of whether they created/contributed to it. I will update the template document on your suggestions, thanks :)

**Comment by aschrijver** [comment]
Thanks @Polarisation and @gkrishnaks !

**Comment by aschrijver** [comment]
The current template is fine and needs no modification for now.
