### ISSUE TITLE
Add privado

### ISSUE THREAD

**Issue by hotrush** [humanetech-community/awesome-humane-tech#40]
I was doing research about search engines and privacy (you know...) that led me to your page 
When I clicked on Cliqz.com, the page was broken...Seems like this search engine is not available in 2020. 

I did some additional research and I found Privado {https://www.privado.com/} a real private search engine, they don't store searches or IPs!

I want to suggest you replace the broken search engine to Privado, I found it was very safe and friendly.

**Comment by aschrijver** [comment]
Could you indicate which link to Cliqz.com was broken? I don't see the particular link, though there are a number of repo's that are in the cliqz organization.

Regarding Privado: We do not yet maintain a category for 'Search engines'. Might be an idea to add that, but this list only accepts open source projects which Privado AFAICS is not.

**Comment by aschrijver** [comment]
No response. Closing.
