### ISSUE TITLE
nayafia/microgrants suitable?

### ISSUE THREAD

**Issue by spekulatius** [humanetech-community/awesome-humane-tech#47]
Hey @aschrijver 

do you think https://github.com/nayafia/microgrants is suitable?

Cheers,
Peter

**Comment by aschrijver** [comment]
Thank you @spekulatius 

This is not directly applicable to awesome-humane-tech list. But I also maintain Delightful project with its sublist of delightful-funding. Though this still hast to pick up more steam (it is a time issue) I have added your suggestion to: https://codeberg.org/teaserbot-labs/delightful-funding/issues/1

**Comment by spekulatius** [comment]
> Thank you @spekulatius
> 
> This is not directly applicable to awesome-humane-tech list. But I also maintain Delightful project with its sublist of delightful-funding. Though this still hast to pick up more steam (it is a time issue) I have added your suggestion to: https://codeberg.org/teaserbot-labs/delightful-funding/issues/1

Awesome, I didn't know you are on codeberg too. I've starred your list there 👍️ 💪️

**Comment by spekulatius** [comment]
Let's close this for now
