### ISSUE TITLE
Exodify URL taken over by spam (but extension/GitHub still ok)

### ISSUE THREAD

**Issue by maxstarkenburg** [humanetech-community/awesome-humane-tech#48]
Thank you for this helpful list. I was clicking through to some that looked of possible interest to me. The line for Exodify goes directly to exodify dot org, but when following that link, I'm taken to a page that's seemingly selling women's apparel/lingerie in Polish. Definitely not what I expected. I imagine the domain expired and got snapped up by somebody fishy. However, searching for the extension in DuckDuckGo, I was able to find https://github.com/FacettsOpen/exodify, and tried out the FF extension, and it seems to work as expected, so I imagine the fishiness is just limited to the domain (I'll submit an issue in that repo next).

**Comment by aschrijver** [comment]
:+1:  Thank you for bringing this to my attention @maxstarkenburg I have updated the link, and will also give a response to https://github.com/FacettsOpen/exodify/issues/9
