### ISSUE TITLE
Remove nudge

### ISSUE THREAD

**Issue by nurgasemetey** [humanetech-community/awesome-humane-tech#52]
Hello,

Nudge asks for payment with banner like this

![Screenshot from 2020-11-17 16-23-39](https://user-images.githubusercontent.com/4669437/99395486-89db1d80-28f1-11eb-8626-748110cd64dc.png)

I think that it annoys and it doesn not add "Freedom or Wellbeing" which is promoted here

**Comment by aschrijver** [comment]
The freedom is as meant by open-source software: "Free as in freedom, not free as in free beer". There is nothing wrong with OSS developers trying to get some income from their hard work. How they do that is a personal choice. You could create an issue on their tracker and suggest a different approach. The developer is also member of our [forum](https://community.humanetech.com). The open source community is having a hard time with commercial parties using their work without contributing much back, and a constructive discussion on OSS revenue models is most welcome.

**Comment by nurgasemetey** [comment]
I totally agree with you about monetizing and unethical commercial parties. I was just surprised that banner appeared when I didn't expect it. Maybe some disclaimer about it would be good.
