### ISSUE TITLE
Add Hide Likes and Intention to Mindfulness section

### ISSUE THREAD

**Issue by MaskyS** [humanetech-community/awesome-humane-tech#63]
Hi, here are two extensions I've been using happily for the last few weeks:

https://addons.mozilla.org/en-US/firefox/addon/hide-likes/
https://addons.mozilla.org/en-US/firefox/addon/intention/

I'd make a PR if I had more time; hope this helps :)

**Comment by aschrijver** [comment]
Thanks for the suggestions, @MaskyS 

Unfortunately the addons do not match the open-source requirements.
I had an earlier interaction with the creator here: #49
