### ISSUE TITLE
Minimal Twitter and MindBell new links

### ISSUE THREAD

**Issue by Mennaruuk** [humanetech-community/awesome-humane-tech#68]
Minimal Twitter: https://twang.dev/minimal-twitter is broken, now it's https://www.wang.sh/minimal-twitter.
MindBell: https://www.dknapps.de/mindbell/ only works once you get rid of www.

**Comment by aschrijver** [comment]
Awesome! Thanks much @Mennaruuk

**Comment by Mennaruuk** [comment]
Anytime!
