### ISSUE TITLE
"Bundled Service Providers" category?

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/awesome-humane-tech#78]
PR #75 typically does not fit the awesome-humane-tech list. But it is an example of an upcoming class of service providers: Those that bundle FOSS software applications, maintain them, and offer them to other people.

I have not yet decided whether a new category like "Bundled Service Providers" is needed, and it can be hard to gauge the awesomeness of the services on offer. Maybe one requirement for inclusion would be that the source code (deployment scripts, etc.) of the provider should be available.

In any case this issue exists to track possible candidates for inclusion.. starting now:

- [Silkky.Cloud](https://www.silkky.cloud): Infrastructure, resources and guides aimed at helping you to protect your privacy against global surveillance.
- [Cloud68](https://cloud68.co/): Reliable open source digital infrastructure
- [OpenDesktop](https://www.opendesktop.org/): Libre Cloud Services.
- [The Good Cloud](https://thegood.cloud/en): Store, sync and share your data while ensuring your privacy.
- [Nomagic](https://nomagic.uk/): Privacy, Libre Software and elbow grease.
- [LibreOps](https://libreops.cc/): Decentralized services and tools that respect users privacy by default.
- [Co-op Cloud](https://coopcloud.tech/): Public interest infrastructure. An alternative to corporate clouds built by tech co-ops.
- [Chatons](https://www.chatons.org/en): A collective that aims to bring together structures offering free, ethical and decentralised online services
- [Autonomic Co-operative](https://autonomic.zone/): Technologies and infrastructure to empower users to make a positive impact on the world

A network of libre hosters: [libreho.st](https://libreho.st/)

**Comment by TheSilkky** [comment]
I agress that source code should be open-source as a requirement, Silkky.Cloud's are [here.](https://github.com/silkkycloud). Would you like me close #75 and open a new one with the bundled category?

**Comment by aschrijver** [comment]
I will close #75 as that will change anyway. But I haven't decided yet, so this issue will hang around for a while longer and collect candidates. If I add a new category here, then Silkky will be top-level entry with both the site and the source.

Another option might be to start a curated sublist to the [delightful project](https://codeberg.org/teaserbot-labs/delightful) which I started as an alternative to Awesome lists. But I lack bandwidth to properly work all the list that I am a maintainer of atm, so I am a bit hesitant.

**Comment by jonatasbaldin** [comment]
hey hey, after chatting a bit with @aschrijver, I built a list here: https://codeberg.org/jonatasbaldin/delightful-libre-hosters

let me know what do you think!

**Comment by TheSilkky** [comment]
@jonatasbaldin Looks really good, thanks for setting this up! :)

**Comment by aschrijver** [comment]
It looks really and I am quite happy and grateful that you set up that delightful list @jonatasbaldin :heart_eyes: 

Your list will be the proper place for the kind of entries that were tracked in this issue, so hereby I am closing it (and along with that @TheSilkky still open PR).
