### ISSUE TITLE
Update PR-template

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/awesome-humane-tech#94]
Add the requirement for single-line entries to the PR template (fix as result of #93 comment).

**Comment by RanchoSMAuth335** [comment]
[[]()]()-

**Comment by RanchoSMAuth335** [comment]
[[]()]()-

**Comment by RanchoSMAuth335** [comment]
- [[]()]()- []() please ![image](https://user-images.githubusercontent.com/101719696/179136500-7de59aac-b4b3-4df0-9239-7ad523fbad4e.jpeg)![image](https://user-images.githubusercontent.com/101719696/179136511-55a73375-fb0d-4c0e-9ae0-ba0b5f64093f.jpeg)

**Comment by aschrijver** [comment]
Codeberg migration. Closing.
