### ISSUE TITLE
Moving to Codeberg

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/awesome-humane-tech#99]
I consider moving this entire curated list away from Github altogether (this repo will then point to the new location). It will then become a [delightful list](https://codeberg.org/teaserbot-labs/delightful) on [Codeberg](https://codeberg.org) instead, and show on the [Delightful Club](https://delightful.club) website too. Note: I created delightful project as alternative to awesome that is only for FOSS, Open Data and Open Science related resources.

**Comment by aschrijver** [comment]
I already maintain [**Delightful Humae Design**](https://codeberg.org/teaserbot-labs/delightful-humane-design) so you can see that as an example. Maybe merging the list makes sense as well, so that I can give all my love to it at one single location.

**Comment by aschrijver** [comment]
Just found that for this move to work Gitea already supports [Issue and PR templates](https://docs.gitea.io/en-us/issue-pull-request-templates/) out-of-the-box.

**Comment by Polarisation** [comment]
The list is popular here and that makes it useful. Delightful lists seems a great idea and I hope it grows, but if you move this list, would it reach as many people? Is it feasible to maintain both an Awesome list and Delightful list in parallel for a period of time to ensure the Delightful list becomes popular before retiring this repo?

**Comment by aschrijver** [comment]
Thanks @Polarisation I will not retire this list, but keep it active with a link-through to the delightful list and an explanation for the reason of the move.

Note that one of the issues with Big Tech is the fact that their dominance and size of their platforms creates very strong network effects and FOMO. This was indeed an important reason why this list has continued to be on Github until now. I.e. stargazing this list is good to spread awareness in that regard.

But time has come to ditch the FOMO. There are important developments that also relate to Codeberg. It is hosted on [Gitea](https://gitea.io), who recently [received a NLnet grant](https://social.gitea.io/@gitea/107576791626052697) to add federation support and become part of the Fediverse. That means that eventually every Gitea code forge will interoperate with others, forming one big distributed 'Github'. And furthermore there is the [Forgefriends community](https://forum.forgefriends.org) that is dedicated to adding federation to other forges, such as Gitlab, Github, Sourcehut, etc.. so that they are all able to interoperate.

**Comment by aschrijver** [comment]
Script that might be useful: https://codeberg.org/librecast/giveupgithub.sh

(Though the importer looks like a better migration path).

**Comment by aschrijver** [comment]
Codeberg migration. Closing.
